const Users = () => [
	{
		id: 1,
		username: "Claude Iranzi",
		email: "claude@gmail.com",
		amount: 400,
		status: "pending",
	},
	{
		id: 2,
		username: "Char john",
		email: "john@gmail.com",
		amount: 500,
		status: "paid",
	},
	{
		id: 3,
		username: "clarissa nadia",
		email: "nadia@gmail.com",
		amount: 700,
		status: "paid",
	},
	{
		id: 4,
		username: "Low kenny",
		email: "kenny@gmail.com",
		amount: 400,
		status: "pending",
	},
	{
		id: 5,
		username: "jean yves",
		email: "yves@gmail.com",
		amount: 800,
		status: "pending",
	},
	{
		id: 6,
		username: "jean claude",
		email: "yves@gmail.com",
		amount: 800,
		status: "paid",
	},
	{
		id: 7,
		username: "smith yves",
		email: "smith@gmail.com",
		amount: 800,
		status: "pending",
	},
	{
		id: 8,
		username: "marcel yves",
		email: "marcel@gmail.com",
		amount: 100,
		status: "paid",
	},
	{
		id: 9,
		username: "marcel yves",
		email: "marcel@gmail.com",
		amount: 100,
		status: "paid",
	},
	{
		id: 10,
		username: "marcel yves",
		email: "marcel@gmail.com",
		amount: 100,
		status: "paid",
	},
	{
		id: 11,
		username: "iranzi yves",
		email: "iranzi@gmail.com",
		amount: 600,
		status: "paid",
	},
];
export default Users